# Generated by Django 3.2.12 on 2023-02-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz_pages.theme'),
        ),
    ]
