# Generated by Django 3.2.12 on 2023-02-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_pages', '0007_choice_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='theme',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_valid_answer',
            field=models.BooleanField(default=False),
        ),
    ]
